### PR TITLE
GH-161 Check if WebJarHandler is already registered

### LINKED ISSUE #161: Multiple Swagger UI's cannot co-exist
There is currently two issues with multiple swagger UIs:

a) one has to create a sub-class of the plugin as otherwise `javalin` wouldn't register it (I will read upon that and mention it over at `javalin`. I guess there are plugins for which only a single instance should exist).
b) this fails as both instances try to add the webjar GET handler.

The former can be counted as a minor inconvenience, the latter, however, is an easy fix which I will provide in due time.

### PR DESCRIPTION
**Pull request by sauterl**
Resolves #161 by carefully checking if such a configured `SwaggerWebJarHandler` already exists and if not, registers _one per_ `SwaggerPlugin`. Includes a unit test to demonstrate and confirm the new behaviour.

In the rare circumstance, that someone already would have a non `SwaggerWebJarHanlder` `GET` handler on the configured swagger webjar route, this implementation would -in my opinion- rightfully fail.

Replaces #162  due to polluted git history.

### CODE REVIEW

File: javalin-plugins/javalin-swagger-plugin/src/main/kotlin/io/javalin/openapi/plugin/swagger/SwaggerPlugin.kt [hunk 1]
```diff
@@ -35,14 +36,17 @@ open class SwaggerPlugin @JvmOverloads constructor(private val configuration: Sw
...
-        val swaggerWebJarHandler = SwaggerWebJarHandler(
-            swaggerWebJarPath = configuration.webJarPath
-        )
-
-        app
-            .get(configuration.uiPath, swaggerHandler, *configuration.roles)
-            .get("${configuration.webJarPath}/*", swaggerWebJarHandler, *configuration.roles)
+        /** Register webjar handler if and only if there isn't already a [SwaggerWebJarHandler] at configured route */
+        val routes = app.javalinServlet().matcher.findEntries(HandlerType.GET, "${configuration.webJarPath}/*")
+        if(routes.isNotEmpty() && routes.first().handler !is SwaggerWebJarHandler){
```
Comment (dzikoysk) [inline javalin-plugins/javalin-swagger-plugin/src/main/kotlin/io/javalin/openapi/plugin/swagger/SwaggerPlugin.kt:44]: It looks like the handler is registered only if there's an entry that matches `${configuration.webJarPath}/*` and the first result is not `SwaggerWebJarHandler`. Am I missing sth? The test checks if response `isNotBlank`, but I think it's just 404 with some default message. It's late and I'm really tired after 🏂, so that's it from me today - I'll try to take a look at it tomorrow/in the weekend.

Comment (sauterl) [reply javalin-plugins/javalin-swagger-plugin/src/main/kotlin/io/javalin/openapi/plugin/swagger/SwaggerPlugin.kt]: Thanks for the comment. Indeed I missed a  `isEmpty` in that condition there.

I added an additional test case to check whether the (new) solution works with more than a shell `Javalin` and in my opinion, this works as intended and doesn't add any side-effects. Or do you see any issues with this approach?

File: javalin-plugins/javalin-swagger-plugin/src/main/kotlin/io/javalin/openapi/plugin/swagger/SwaggerPlugin.kt [hunk 2]
```diff
@@ -35,14 +36,17 @@ open class SwaggerPlugin @JvmOverloads constructor(private val configuration: Sw
...
-        val swaggerWebJarHandler = SwaggerWebJarHandler(
-            swaggerWebJarPath = configuration.webJarPath
-        )
-
-        app
-            .get(configuration.uiPath, swaggerHandler, *configuration.roles)
-            .get("${configuration.webJarPath}/*", swaggerWebJarHandler, *configuration.roles)
+        /** Register webjar handler if and only if there isn't already a [SwaggerWebJarHandler] at configured route */
+        val routes = app.javalinServlet().matcher.findEntries(HandlerType.GET, "${configuration.webJarPath}/*")
+        if(routes.isEmpty() || (routes.isNotEmpty() && routes.first().handler !is SwaggerWebJarHandler)){
```
Comment (dzikoysk) [inline javalin-plugins/javalin-swagger-plugin/src/main/kotlin/io/javalin/openapi/plugin/swagger/SwaggerPlugin.kt:44]: I think it could be simply replaced with sth like: `routes.none { it is SwaggerWebJarHandler }` 🤔

File: javalin-plugins/javalin-swagger-plugin/src/test/kotlin/io/javalin/openapi/plugin/swagger/SwaggerPluginTest.kt [hunk 3]
```diff
@@ -48,4 +48,117 @@ internal class SwaggerPluginTest {
...
+            it.plugins.register(SwaggerPlugin(swaggerConfiguration))
+            it.plugins.register(otherConfiguration)
+        }
+            .start(8080)
+            .use{
+                val javalinHost = "http://localhost:8080"
+
+                val webjarCssRoute = "/webjars/swagger-ui/${swaggerConfiguration.version}/swagger-ui.css"
+                val webjarJsRoute = "/webjars/swagger-ui/${swaggerConfiguration.version}/swagger-ui-bundle.js"
+                val webjarJsStandaloneRoute = "/webjars/swagger-ui/${swaggerConfiguration.version}/swagger-ui-standalone-preset.js"
```
Comment (dzikoysk) [inline javalin-plugins/javalin-swagger-plugin/src/test/kotlin/io/javalin/openapi/plugin/swagger/SwaggerPluginTest.kt:65]: I think it'd be enough to test just one resource here, in the end all of them come from the same webjar bundle

**Review by dzikoysk — CHANGES_REQUESTED** [review]

**Comment by dzikoysk** [comment]
Thanks! I've applied some changes we've spoked about in cr.
